# SPDX-License-Identifier: MIT
# Copyright (c) 2024 Phish-Sim Project

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Backend API metrics
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # ML Service metrics
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Visual Service metrics
  - job_name: 'visual-service'
    static_configs:
      - targets: ['visual-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Inference Service metrics
  - job_name: 'inference-service'
    static_configs:
      - targets: ['inference-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']